fix: restructre code

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -8,4 +8,25 @@ plugin_dir=$(dirname "$(dirname "$current_script_path")")
 # shellcheck source=./lib/utils.bash
 source "${plugin_dir}/lib/utils.bash"
 
+mkdir -p "$ASDF_DOWNLOAD_PATH"
+
+# TODO: Adapt this to proper extension and adapt extracting strategy.
+release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+
+# Build url
+url="$GH_REPO/releases/download/v${ASDF_INSTALL_VERSION}/stackit-cli_${ASDF_INSTALL_VERSION}_$(get_arch)_$(get_cpu).tar.gz"
+
+# Download tar.gz file to the download directory
+echo "* Downloading $TOOL_NAME release $ASDF_INSTALL_VERSION..."
+curl "${curl_opts[@]}" -o "$release_file" -C - "$url" || fail "Could not download $url"
+
+#  Extract contents of tar.gz file into the download directory
+echo "* Extracting $TOOL_NAME release $ASDF_INSTALL_VERSION..."
+tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" stackit || fail "Could not extract $release_file"
+
+# Remove the tar.gz file since we don't need to keep it
+rm "$release_file"
+
+# Install version
+echo "* Installing $TOOL_NAME release $ASDF_INSTALL_VERSION..."
 install_version "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
